/*
    LssclM2M - http://www.lsscl.com
    Copyright (C) 2006-2011 Lsscl ES Technologies Inc.
     
    
     
     
     
     

     
     
     
     

     
    
 */
package com.serotonin.mango.db.upgrade;

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.serotonin.mango.db.DatabaseAccess;

/**
 *  
 */
public class Upgrade1_6_4 extends DBUpgrade {
    private final Log log = LogFactory.getLog(getClass());

    @Override
    public void upgrade() throws Exception {
        OutputStream out = createUpdateLogOutputStream("1_6_4");

        log.info("Running script 1");
        runScript(script1, out);

        log.info("Running script 2");
        Map<String, String[]> script2 = new HashMap<String, String[]>();
        script2.put(DatabaseAccess.DatabaseType.DERBY.name(), derbyScript2);
        script2.put(DatabaseAccess.DatabaseType.MYSQL.name(), mysqlScript2);
        runScript(script2, out);

        out.flush();
        out.close();
    }

    @Override
    protected String getNewSchemaVersion() {
        return "1.7.0";
    }

    private static String[] script1 = { "alter table users add column receiveOwnAuditEvents char(1);",
            "update users set receiveOwnAuditEvents='Y';", };

    private static String[] derbyScript2 = { "alter table users alter receiveOwnAuditEvents not null;",

    "create table pointLinks (", "  id int not null generated by default as identity (start with 1, increment by 1),",
            "  xid varchar(20) not null,", "  sourcePointId int not null,", "  targetPointId int not null,",
            "  script clob,", "  eventType int not null,", "  disabled char(1) not null", ");",
            "alter table pointLinks add constraint pointLinksPk primary key (id);",
            "alter table pointLinks add constraint pointLinksUn1 unique (xid);", };

    private static String[] mysqlScript2 = { "alter table users modify receiveOwnAuditEvents char(1) not null;",

    "create table pointLinks (", "  id int not null auto_increment,", "  xid varchar(20) not null,",
            "  sourcePointId int not null,", "  targetPointId int not null,", "  script longtext,",
            "  eventType int not null,", "  disabled char(1) not null,", "  primary key (id)", ") engine=InnoDB;",
            "alter table pointLinks add constraint pointLinksUn1 unique (xid);", };
}
